export const ths: string[] = ['Name', 'Status', 'Connect', 'Scolarship']
export const rows: {
	name: string
	status: string
	connect: string
	scolarship: string
}[] = [
	{ name: 'home', status: 'fail', connect: 'Bind', scolarship: 'school' },
	{ name: 'home', status: 'fail', connect: 'Bind', scolarship: 'school' },
	{ name: 'home', status: 'fail', connect: 'Bind', scolarship: 'school' },
	{ name: 'home', status: 'fail', connect: 'Bind', scolarship: 'school' },
	{ name: 'home', status: 'fail', connect: 'Bind', scolarship: 'school' },
	{ name: 'home', status: 'fail', connect: 'Bind', scolarship: 'school' },
	{ name: 'home', status: 'fail', connect: 'Bind', scolarship: 'school' },
	{ name: 'home', status: 'fail', connect: 'Bind', scolarship: 'school' },
	{ name: 'home', status: 'fail', connect: 'Bind', scolarship: 'school' },
	{ name: 'home', status: 'fail', connect: 'Bind', scolarship: 'school' },
	{ name: 'home', status: 'fail', connect: 'Bind', scolarship: 'school' },
	{ name: 'home', status: 'fail', connect: 'Bind', scolarship: 'school' },
	{ name: 'home', status: 'fail', connect: 'Bind', scolarship: 'school' },
	{ name: 'home', status: 'fail', connect: 'Bind', scolarship: 'school' },
	{ name: 'home', status: 'fail', connect: 'Bind', scolarship: 'school' },
	{ name: 'home', status: 'fail', connect: 'Bind', scolarship: 'school' },
	{ name: 'home', status: 'fail', connect: 'Bind', scolarship: 'school' },
	{ name: 'home', status: 'fail', connect: 'Bind', scolarship: 'school' },
	{ name: 'home', status: 'fail', connect: 'Bind', scolarship: 'school' },
	{ name: 'home', status: 'fail', connect: 'Bind', scolarship: 'school' },
	{ name: 'home', status: 'fail', connect: 'Bind', scolarship: 'school' },
	{ name: 'home', status: 'fail', connect: 'Bind', scolarship: 'school' },
	{ name: 'home', status: 'fail', connect: 'Bind', scolarship: 'school' },
	{ name: 'home', status: 'fail', connect: 'Bind', scolarship: 'school' },
	{ name: 'home', status: 'fail', connect: 'Bind', scolarship: 'school' },
	{ name: 'home', status: 'fail', connect: 'Bind', scolarship: 'school' },
	{ name: 'home', status: 'fail', connect: 'Bind', scolarship: 'school' },
	{ name: 'home', status: 'fail', connect: 'Bind', scolarship: 'school' },
	{ name: 'home', status: 'fail', connect: 'Bind', scolarship: 'school' },
	{ name: 'home', status: 'fail', connect: 'Bind', scolarship: 'school' },
	{ name: 'home', status: 'fail', connect: 'Bind', scolarship: 'school' },
	{ name: 'home', status: 'fail', connect: 'Bind', scolarship: 'school' },
	{ name: 'home', status: 'fail', connect: 'Bind', scolarship: 'school' },
	{ name: 'home', status: 'fail', connect: 'Bind', scolarship: 'school' },
	{ name: 'home', status: 'fail', connect: 'Bind', scolarship: 'school' },
	{ name: 'home', status: 'fail', connect: 'Bind', scolarship: 'school' },
	{ name: 'home', status: 'fail', connect: 'Bind', scolarship: 'school' },
	{ name: 'home', status: 'fail', connect: 'Bind', scolarship: 'school' },
	{ name: 'home', status: 'fail', connect: 'Bind', scolarship: 'school' },
	{ name: 'home', status: 'fail', connect: 'Bind', scolarship: 'school' },
	{ name: 'home', status: 'fail', connect: 'Bind', scolarship: 'school' },
	{ name: 'home', status: 'fail', connect: 'Bind', scolarship: 'school' },
	{ name: 'home', status: 'fail', connect: 'Bind', scolarship: 'school' },
	{ name: 'home', status: 'fail', connect: 'Bind', scolarship: 'school' },
	{ name: 'home', status: 'fail', connect: 'Bind', scolarship: 'school' },
	{ name: 'home', status: 'fail', connect: 'Bind', scolarship: 'school' },
]
